[2019-08-03 13:56:15] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/http-kernel/EventListener/RouterListener.php line 141 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/http-kernel/EventListener/RouterListener.php:141, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-08-03 16:10:08] request.INFO: Matched route "userataire_index". {"route":"userataire_index","route_parameters":{"_route":"userataire_index","_controller":"App\\Controller\\PrestataireController::ajout"},"request_uri":"http://localhost/api/ajout","method":"POST"} []
[2019-08-03 16:10:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid json message received" at /home/seynabou/Documents/neldamoney_solo/vendor/friendsofsymfony/rest-bundle/EventListener/BodyListener.php line 115 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): Invalid json message received at /home/seynabou/Documents/neldamoney_solo/vendor/friendsofsymfony/rest-bundle/EventListener/BodyListener.php:115)"} []
[2019-08-03 16:16:32] request.INFO: Matched route "userataire_index". {"route":"userataire_index","route_parameters":{"_route":"userataire_index","_controller":"App\\Controller\\PrestataireController::ajout"},"request_uri":"http://localhost/api/ajout","method":"POST"} []
[2019-08-03 16:16:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid json message received" at /home/seynabou/Documents/neldamoney_solo/vendor/friendsofsymfony/rest-bundle/EventListener/BodyListener.php line 115 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): Invalid json message received at /home/seynabou/Documents/neldamoney_solo/vendor/friendsofsymfony/rest-bundle/EventListener/BodyListener.php:115)"} []
[2019-08-03 16:17:09] request.INFO: Matched route "userataire_index". {"route":"userataire_index","route_parameters":{"_route":"userataire_index","_controller":"App\\Controller\\PrestataireController::ajout"},"request_uri":"http://localhost/api/ajout","method":"POST"} []
[2019-08-03 16:17:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid json message received" at /home/seynabou/Documents/neldamoney_solo/vendor/friendsofsymfony/rest-bundle/EventListener/BodyListener.php line 115 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): Invalid json message received at /home/seynabou/Documents/neldamoney_solo/vendor/friendsofsymfony/rest-bundle/EventListener/BodyListener.php:115)"} []
[2019-08-03 16:19:08] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-03 16:19:08] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-03 16:19:08] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:19:08] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:19:09] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-08-03 16:19:09] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-http/Firewall/AccessListener.php:72)"} []
[2019-08-03 16:19:09] security.DEBUG: Calling Authentication entry point. [] []
[2019-08-03 16:26:23] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-03 16:26:23] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-03 16:26:23] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:26:23] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:26:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-08-03 16:26:23] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-http/Firewall/AccessListener.php:72)"} []
[2019-08-03 16:26:23] security.DEBUG: Calling Authentication entry point. [] []
[2019-08-03 16:27:06] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-03 16:27:06] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-03 16:27:06] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:27:06] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:27:06] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-08-03 16:27:06] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-http/Firewall/AccessListener.php:72)"} []
[2019-08-03 16:27:06] security.DEBUG: Calling Authentication entry point. [] []
[2019-08-03 16:28:44] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-03 16:28:44] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-03 16:28:44] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:28:44] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:28:44] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-08-03 16:28:44] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-http/Firewall/AccessListener.php:72)"} []
[2019-08-03 16:28:44] security.DEBUG: Calling Authentication entry point. [] []
[2019-08-03 16:29:33] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-03 16:29:33] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-03 16:29:33] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:29:33] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:29:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-08-03 16:29:33] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-http/Firewall/AccessListener.php:72)"} []
[2019-08-03 16:29:33] security.DEBUG: Calling Authentication entry point. [] []
[2019-08-03 16:31:14] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-03 16:31:14] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-03 16:31:14] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:31:14] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:31:14] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-03 16:31:15] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.partenaire_id AS partenaire_id_12 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-03 16:31:15] doctrine.DEBUG: SELECT t0.id AS id_1, t0.rs AS rs_2, t0.nom AS nom_3, t0.adresse AS adresse_4, t0.statut AS statut_5, t0.ninea AS ninea_6 FROM prestataire t0 WHERE t0.id = ? [2] []
[2019-08-03 16:31:15] doctrine.DEBUG: "START TRANSACTION" [] []
[2019-08-03 16:31:15] doctrine.DEBUG: INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"1":"sarl","2":["ADMIN"],"3":"$argon2i$v=19$m=1024,t=2,p [...]","4":77788784,"5":"adida","6":"seck","7":"aroser","8":777777,"9":"actif","10":"dija@gmail.com","11":2} []
[2019-08-03 16:31:15] doctrine.DEBUG: "ROLLBACK" [] []
[2019-08-03 16:31:15] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["sarl", "[\"ADMIN\"]", "$argon2i$v=19$m=1024,t=2,p=2$OTVSVElkS3Nzc3M4eUtOMA$uFY0PhfGlCTid3k6IHEJnT59K6UZ1xy\/EiwW14VqX+U", 77788784, "adida", "seck", "aroser", 777777, "actif", "dija@gmail.com", 2]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sarl' for key 'UNIQ_8D93D649F85E0677'" at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 55 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"sarl\", \"[\\\"ADMIN\\\"]\", \"$argon2i$v=19$m=1024,t=2,p=2$OTVSVElkS3Nzc3M4eUtOMA$uFY0PhfGlCTid3k6IHEJnT59K6UZ1xy\\/EiwW14VqX+U\", 77788784, \"adida\", \"seck\", \"aroser\", 777777, \"actif\", \"dija@gmail.com\", 2]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sarl' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:55, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sarl' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sarl' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} []
[2019-08-03 16:35:30] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-03 16:35:30] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-03 16:35:30] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:35:30] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:35:30] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-03 16:35:31] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.partenaire_id AS partenaire_id_12 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-03 16:35:31] doctrine.DEBUG: SELECT t0.id AS id_1, t0.rs AS rs_2, t0.nom AS nom_3, t0.adresse AS adresse_4, t0.statut AS statut_5, t0.ninea AS ninea_6 FROM prestataire t0 WHERE t0.id = ? [2] []
[2019-08-03 16:35:31] doctrine.DEBUG: "START TRANSACTION" [] []
[2019-08-03 16:35:31] doctrine.DEBUG: INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"1":"sarl","2":["ADMIN"],"3":"$argon2i$v=19$m=1024,t=2,p [...]","4":77788784,"5":"adida","6":"seck","7":"aroser","8":777777,"9":"actif","10":"dija@gmail.com","11":2} []
[2019-08-03 16:35:31] doctrine.DEBUG: "ROLLBACK" [] []
[2019-08-03 16:35:31] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["sarl", "[\"ADMIN\"]", "$argon2i$v=19$m=1024,t=2,p=2$L0RHUlNUMHRCNmlKeU1NYg$O3G\/hSh0I\/Ej4gYV6LNyoZkJhXnd3gzLCMiGUILsOTk", 77788784, "adida", "seck", "aroser", 777777, "actif", "dija@gmail.com", 2]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sarl' for key 'UNIQ_8D93D649F85E0677'" at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 55 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"sarl\", \"[\\\"ADMIN\\\"]\", \"$argon2i$v=19$m=1024,t=2,p=2$L0RHUlNUMHRCNmlKeU1NYg$O3G\\/hSh0I\\/Ej4gYV6LNyoZkJhXnd3gzLCMiGUILsOTk\", 77788784, \"adida\", \"seck\", \"aroser\", 777777, \"actif\", \"dija@gmail.com\", 2]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sarl' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:55, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sarl' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sarl' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} []
[2019-08-03 16:38:27] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-03 16:38:27] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-03 16:38:27] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:38:27] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:38:27] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-03 16:38:27] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.partenaire_id AS partenaire_id_12 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-03 16:38:27] doctrine.DEBUG: SELECT t0.id AS id_1, t0.rs AS rs_2, t0.nom AS nom_3, t0.adresse AS adresse_4, t0.statut AS statut_5, t0.ninea AS ninea_6 FROM prestataire t0 WHERE t0.id = ? [2] []
[2019-08-03 16:38:27] doctrine.DEBUG: "START TRANSACTION" [] []
[2019-08-03 16:38:27] doctrine.DEBUG: INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"1":"sarl","2":["ADMIN"],"3":"$argon2i$v=19$m=1024,t=2,p [...]","4":77788784,"5":"adida","6":"seck","7":"aroser","8":777777,"9":"actif","10":"dija@gmail.com","11":2} []
[2019-08-03 16:38:27] doctrine.DEBUG: "ROLLBACK" [] []
[2019-08-03 16:38:28] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["sarl", "[\"ADMIN\"]", "$argon2i$v=19$m=1024,t=2,p=2$cUdaLlpaa0xSMXpwU0pFLw$rjmpoPBlx4QQZa2SVG9yNOzrHeiIixC2MbeYyu6w8kw", 77788784, "adida", "seck", "aroser", 777777, "actif", "dija@gmail.com", 2]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sarl' for key 'UNIQ_8D93D649F85E0677'" at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 55 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"sarl\", \"[\\\"ADMIN\\\"]\", \"$argon2i$v=19$m=1024,t=2,p=2$cUdaLlpaa0xSMXpwU0pFLw$rjmpoPBlx4QQZa2SVG9yNOzrHeiIixC2MbeYyu6w8kw\", 77788784, \"adida\", \"seck\", \"aroser\", 777777, \"actif\", \"dija@gmail.com\", 2]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sarl' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:55, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sarl' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sarl' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} []
[2019-08-03 16:40:21] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-03 16:40:21] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-03 16:40:21] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:40:21] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:40:21] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-03 16:40:21] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.partenaire_id AS partenaire_id_12 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-03 16:40:21] doctrine.DEBUG: SELECT t0.id AS id_1, t0.rs AS rs_2, t0.nom AS nom_3, t0.adresse AS adresse_4, t0.statut AS statut_5, t0.ninea AS ninea_6 FROM prestataire t0 WHERE t0.id = ? [2] []
[2019-08-03 16:40:21] doctrine.DEBUG: "START TRANSACTION" [] []
[2019-08-03 16:40:21] doctrine.DEBUG: INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"1":"sarle","2":["ADMIN"],"3":"$argon2i$v=19$m=1024,t=2,p [...]","4":77788784,"5":"adida","6":"seck","7":"aroser","8":777777,"9":"actif","10":"dija@gmail.com","11":2} []
[2019-08-03 16:40:21] doctrine.DEBUG: "COMMIT" [] []
[2019-08-03 16:41:54] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-03 16:41:54] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-03 16:41:54] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:41:54] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-03 16:41:54] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-03 16:41:54] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.partenaire_id AS partenaire_id_12 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-03 16:41:54] doctrine.DEBUG: SELECT t0.id AS id_1, t0.rs AS rs_2, t0.nom AS nom_3, t0.adresse AS adresse_4, t0.statut AS statut_5, t0.ninea AS ninea_6 FROM prestataire t0 WHERE t0.id = ? [2] []
[2019-08-03 16:41:54] doctrine.DEBUG: "START TRANSACTION" [] []
[2019-08-03 16:41:54] doctrine.DEBUG: INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"1":"sarlem","2":["ADMIN"],"3":"$argon2i$v=19$m=1024,t=2,p [...]","4":77788784,"5":"adida","6":"seck","7":"aroser","8":777777,"9":"actif","10":"dija@gmail.com","11":2} []
[2019-08-03 16:41:54] doctrine.DEBUG: "COMMIT" [] []
[2019-08-05 00:30:49] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-05 00:30:49] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 00:30:49] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:30:49] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:30:49] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-05 00:30:49] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-05 00:30:49] security.INFO: Basic authentication failed for user. {"username":"ndioufa","exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"ndioufa\" not found. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:61)"} []
[2019-08-05 00:30:50] request.INFO: Matched route "depot". {"route":"depot","route_parameters":{"_route":"depot","_controller":"App\\Controller\\DepotController::depot"},"request_uri":"http://localhost/api/depot","method":"POST"} []
[2019-08-05 00:30:50] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 00:30:50] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:30:50] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:30:50] security.INFO: Basic authentication Authorization header found for user. {"username":"kya"} []
[2019-08-05 00:30:50] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["kya"] []
[2019-08-05 00:30:50] security.INFO: Basic authentication failed for user. {"username":"kya","exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"kya\" not found. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:61)"} []
[2019-08-05 00:31:54] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-05 00:31:54] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 00:31:54] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:31:54] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:31:54] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-05 00:31:54] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-05 00:31:54] security.INFO: Basic authentication failed for user. {"username":"ndioufa","exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"ndioufa\" not found. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:61)"} []
[2019-08-05 00:32:14] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-05 00:32:14] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 00:32:14] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:32:14] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:32:14] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-05 00:32:14] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-05 00:32:14] security.INFO: Basic authentication failed for user. {"username":"ndioufa","exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"ndioufa\" not found. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:61)"} []
[2019-08-05 00:32:40] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-05 00:32:40] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 00:32:40] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:32:40] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:32:40] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-05 00:32:40] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-05 00:32:40] security.INFO: Basic authentication failed for user. {"username":"ndioufa","exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"ndioufa\" not found. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:61)"} []
[2019-08-05 00:34:15] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-05 00:34:15] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 00:34:15] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:34:15] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:34:15] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-05 00:34:15] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-05 00:34:15] security.INFO: Basic authentication failed for user. {"username":"ndioufa","exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"ndioufa\" not found. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:61)"} []
[2019-08-05 00:34:46] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-05 00:34:46] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 00:34:46] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:34:46] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:34:46] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-05 00:34:46] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-05 00:34:46] security.INFO: Basic authentication failed for user. {"username":"ndioufa","exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"ndioufa\" not found. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:61)"} []
[2019-08-05 00:49:48] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-05 00:49:48] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 00:49:48] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:49:48] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:49:48] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-05 00:49:48] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-05 00:49:48] security.INFO: Basic authentication failed for user. {"username":"ndioufa","exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"ndioufa\" not found. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:61)"} []
[2019-08-05 00:49:48] request.INFO: Matched route "userataire_index". {"route":"userataire_index","route_parameters":{"_route":"userataire_index","_controller":"App\\Controller\\PrestataireController::ajout"},"request_uri":"http://localhost/api/ajout","method":"POST"} []
[2019-08-05 00:49:48] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 00:49:48] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:49:48] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 00:49:48] security.INFO: Basic authentication Authorization header found for user. {"username":"zeynab"} []
[2019-08-05 00:49:48] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["zeynab"] []
[2019-08-05 00:49:48] doctrine.DEBUG: "START TRANSACTION" [] []
[2019-08-05 00:49:48] doctrine.DEBUG: INSERT INTO prestataire (rs, nom, adresse, statut, ninea) VALUES (?, ?, ?, ?, ?) {"1":"sa","2":"diop","3":"km","4":"actif","5":"6e54k"} []
[2019-08-05 00:49:48] doctrine.DEBUG: INSERT INTO compte (numbcompte, solde, partenaire_id) VALUES (?, ?, ?) {"1":497708,"2":0,"3":14} []
[2019-08-05 00:49:48] doctrine.DEBUG: INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"1":"kya","2":["ROLE_ADMIN"],"3":"$argon2i$v=19$m=1024,t=2,p [...]","4":7747544,"5":"diop","6":"kya","7":"km","8":748500222,"9":"actif","10":"kd@gmail.com","11":null,"12":null,"13":14} []
[2019-08-05 00:49:48] doctrine.DEBUG: "COMMIT" [] []
[2019-08-05 10:22:21] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-05 10:22:21] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 10:22:21] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 10:22:21] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 10:22:21] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-05 10:22:21] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-05 10:22:21] security.INFO: Basic authentication failed for user. {"username":"ndioufa","exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"ndioufa\" not found. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:61)"} []
[2019-08-05 10:22:22] request.INFO: Matched route "userataire_index". {"route":"userataire_index","route_parameters":{"_route":"userataire_index","_controller":"App\\Controller\\PrestataireController::ajout"},"request_uri":"http://localhost/api/ajout","method":"POST"} []
[2019-08-05 10:22:22] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 10:22:22] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 10:22:22] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 10:22:22] security.INFO: Basic authentication Authorization header found for user. {"username":"zeynab"} []
[2019-08-05 10:22:22] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["zeynab"] []
[2019-08-05 10:22:22] doctrine.DEBUG: "START TRANSACTION" [] []
[2019-08-05 10:22:22] doctrine.DEBUG: INSERT INTO prestataire (rs, nom, adresse, statut, ninea) VALUES (?, ?, ?, ?, ?) {"1":"sa","2":"diop","3":"km","4":"actif","5":"6e54k"} []
[2019-08-05 10:22:22] doctrine.DEBUG: INSERT INTO compte (numbcompte, solde, partenaire_id) VALUES (?, ?, ?) {"1":103588,"2":0,"3":15} []
[2019-08-05 10:22:22] doctrine.DEBUG: INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"1":"kya","2":["ROLE_ADMIN"],"3":"$argon2i$v=19$m=1024,t=2,p [...]","4":7747544,"5":"diop","6":"kya","7":"km","8":748500222,"9":"actif","10":"kd@gmail.com","11":null,"12":null,"13":15} []
[2019-08-05 10:22:22] doctrine.DEBUG: "ROLLBACK" [] []
[2019-08-05 10:22:22] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["kya", "[\"ROLE_ADMIN\"]", "$argon2i$v=19$m=1024,t=2,p=2$Z09tZVN1djJiZHVPQlJDQw$ZHHt0ISFauVdbLGHgpo\/fkUiv+nB64JMJRc2dKQXfjw", 7747544, "diop", "kya", "km", 748500222, "actif", "kd@gmail.com", null, null, 15]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677'" at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 55 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"kya\", \"[\\\"ROLE_ADMIN\\\"]\", \"$argon2i$v=19$m=1024,t=2,p=2$Z09tZVN1djJiZHVPQlJDQw$ZHHt0ISFauVdbLGHgpo\\/fkUiv+nB64JMJRc2dKQXfjw\", 7747544, \"diop\", \"kya\", \"km\", 748500222, \"actif\", \"kd@gmail.com\", null, null, 15]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:55, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} []
[2019-08-05 10:22:36] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-05 10:22:36] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 10:22:36] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 10:22:36] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 10:22:36] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-05 10:22:36] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-05 10:22:36] security.INFO: Basic authentication failed for user. {"username":"ndioufa","exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"ndioufa\" not found. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:61)"} []
[2019-08-05 10:22:36] request.INFO: Matched route "userataire_index". {"route":"userataire_index","route_parameters":{"_route":"userataire_index","_controller":"App\\Controller\\PrestataireController::ajout"},"request_uri":"http://localhost/api/ajout","method":"POST"} []
[2019-08-05 10:22:36] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 10:22:36] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 10:22:36] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 10:22:36] security.INFO: Basic authentication Authorization header found for user. {"username":"zeynab"} []
[2019-08-05 10:22:36] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["zeynab"] []
[2019-08-05 10:22:36] doctrine.DEBUG: "START TRANSACTION" [] []
[2019-08-05 10:22:36] doctrine.DEBUG: INSERT INTO prestataire (rs, nom, adresse, statut, ninea) VALUES (?, ?, ?, ?, ?) {"1":"sa","2":"diop","3":"km","4":"actif","5":"6e54k"} []
[2019-08-05 10:22:36] doctrine.DEBUG: INSERT INTO compte (numbcompte, solde, partenaire_id) VALUES (?, ?, ?) {"1":924430,"2":0,"3":16} []
[2019-08-05 10:22:36] doctrine.DEBUG: INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"1":"kya","2":["ROLE_ADMIN"],"3":"$argon2i$v=19$m=1024,t=2,p [...]","4":7747544,"5":"diop","6":"kya","7":"km","8":748500222,"9":"actif","10":"kd@gmail.com","11":null,"12":null,"13":16} []
[2019-08-05 10:22:36] doctrine.DEBUG: "ROLLBACK" [] []
[2019-08-05 10:22:37] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["kya", "[\"ROLE_ADMIN\"]", "$argon2i$v=19$m=1024,t=2,p=2$cnlpZnJweE5SZkZZSHpDTQ$Wsb7CcAO7cyqiu6O6NDnJJEDW0UkJNj75765BUTTRVg", 7747544, "diop", "kya", "km", 748500222, "actif", "kd@gmail.com", null, null, 16]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677'" at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 55 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"kya\", \"[\\\"ROLE_ADMIN\\\"]\", \"$argon2i$v=19$m=1024,t=2,p=2$cnlpZnJweE5SZkZZSHpDTQ$Wsb7CcAO7cyqiu6O6NDnJJEDW0UkJNj75765BUTTRVg\", 7747544, \"diop\", \"kya\", \"km\", 748500222, \"actif\", \"kd@gmail.com\", null, null, 16]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:55, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} []
[2019-08-05 11:03:50] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-05 11:03:50] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 11:03:50] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:03:50] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:03:50] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-05 11:03:50] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-05 11:03:50] security.INFO: Basic authentication failed for user. {"username":"ndioufa","exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"ndioufa\" not found. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:61)"} []
[2019-08-05 11:03:50] request.INFO: Matched route "userataire_index". {"route":"userataire_index","route_parameters":{"_route":"userataire_index","_controller":"App\\Controller\\PrestataireController::ajout"},"request_uri":"http://localhost/api/ajout","method":"POST"} []
[2019-08-05 11:03:50] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 11:03:50] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:03:50] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:03:50] security.INFO: Basic authentication Authorization header found for user. {"username":"zeynab"} []
[2019-08-05 11:03:50] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["zeynab"] []
[2019-08-05 11:03:50] doctrine.DEBUG: "START TRANSACTION" [] []
[2019-08-05 11:03:50] doctrine.DEBUG: INSERT INTO prestataire (rs, nom, adresse, statut, ninea) VALUES (?, ?, ?, ?, ?) {"1":"sa","2":"diop","3":"km","4":"actif","5":"6e54k"} []
[2019-08-05 11:03:50] doctrine.DEBUG: INSERT INTO compte (numbcompte, solde, partenaire_id) VALUES (?, ?, ?) {"1":693276,"2":0,"3":17} []
[2019-08-05 11:03:50] doctrine.DEBUG: INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"1":"kya","2":["ROLE_ADMIN"],"3":"$argon2i$v=19$m=1024,t=2,p [...]","4":7747544,"5":"diop","6":"kya","7":"km","8":748500222,"9":"actif","10":"kd@gmail.com","11":null,"12":null,"13":17} []
[2019-08-05 11:03:50] doctrine.DEBUG: "ROLLBACK" [] []
[2019-08-05 11:03:50] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["kya", "[\"ROLE_ADMIN\"]", "$argon2i$v=19$m=1024,t=2,p=2$UGxGVEpneTVJV3NIWGFVQg$2jsluzSX16N+9E7DjYJDGcClcvX1eJUIi22SsagBOZ0", 7747544, "diop", "kya", "km", 748500222, "actif", "kd@gmail.com", null, null, 17]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677'" at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 55 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"kya\", \"[\\\"ROLE_ADMIN\\\"]\", \"$argon2i$v=19$m=1024,t=2,p=2$UGxGVEpneTVJV3NIWGFVQg$2jsluzSX16N+9E7DjYJDGcClcvX1eJUIi22SsagBOZ0\", 7747544, \"diop\", \"kya\", \"km\", 748500222, \"actif\", \"kd@gmail.com\", null, null, 17]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:55, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} []
[2019-08-05 11:04:16] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-05 11:04:16] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 11:04:16] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:04:16] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:04:16] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-05 11:04:16] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-05 11:04:16] security.INFO: Basic authentication failed for user. {"username":"ndioufa","exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"ndioufa\" not found. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:61)"} []
[2019-08-05 11:04:16] request.INFO: Matched route "userataire_index". {"route":"userataire_index","route_parameters":{"_route":"userataire_index","_controller":"App\\Controller\\PrestataireController::ajout"},"request_uri":"http://localhost/api/ajout","method":"POST"} []
[2019-08-05 11:04:16] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 11:04:16] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:04:16] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:04:16] security.INFO: Basic authentication Authorization header found for user. {"username":"zeynab"} []
[2019-08-05 11:04:16] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["zeynab"] []
[2019-08-05 11:04:16] doctrine.DEBUG: "START TRANSACTION" [] []
[2019-08-05 11:04:16] doctrine.DEBUG: INSERT INTO prestataire (rs, nom, adresse, statut, ninea) VALUES (?, ?, ?, ?, ?) {"1":"sa","2":"diop","3":"km","4":"actif","5":"6e54k"} []
[2019-08-05 11:04:16] doctrine.DEBUG: INSERT INTO compte (numbcompte, solde, partenaire_id) VALUES (?, ?, ?) {"1":431419,"2":0,"3":18} []
[2019-08-05 11:04:16] doctrine.DEBUG: INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"1":"kya","2":["ROLE_ADMIN"],"3":"$argon2i$v=19$m=1024,t=2,p [...]","4":7747544,"5":"diop","6":"kya","7":"km","8":748500222,"9":"actif","10":"kd@gmail.com","11":null,"12":null,"13":18} []
[2019-08-05 11:04:16] doctrine.DEBUG: "ROLLBACK" [] []
[2019-08-05 11:04:16] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["kya", "[\"ROLE_ADMIN\"]", "$argon2i$v=19$m=1024,t=2,p=2$eGVaSUFwOWtkL3V4ODhmUQ$P3f2L4+Aa0IXE8WVY2bACdPmrVjwe4F3HpTmF0gmxQI", 7747544, "diop", "kya", "km", 748500222, "actif", "kd@gmail.com", null, null, 18]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677'" at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 55 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"kya\", \"[\\\"ROLE_ADMIN\\\"]\", \"$argon2i$v=19$m=1024,t=2,p=2$eGVaSUFwOWtkL3V4ODhmUQ$P3f2L4+Aa0IXE8WVY2bACdPmrVjwe4F3HpTmF0gmxQI\", 7747544, \"diop\", \"kya\", \"km\", 748500222, \"actif\", \"kd@gmail.com\", null, null, 18]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:55, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} []
[2019-08-05 11:07:08] request.INFO: Matched route "userataire_index". {"route":"userataire_index","route_parameters":{"_route":"userataire_index","_controller":"App\\Controller\\PrestataireController::ajout"},"request_uri":"http://localhost/api/ajout","method":"POST"} []
[2019-08-05 11:07:08] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 11:07:08] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:07:08] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:07:08] security.INFO: Basic authentication Authorization header found for user. {"username":"zeynab"} []
[2019-08-05 11:07:08] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["zeynab"] []
[2019-08-05 11:07:08] doctrine.DEBUG: "START TRANSACTION" [] []
[2019-08-05 11:07:08] doctrine.DEBUG: INSERT INTO prestataire (rs, nom, adresse, statut, ninea) VALUES (?, ?, ?, ?, ?) {"1":"sa","2":"diop","3":"km","4":"actif","5":"6e54k"} []
[2019-08-05 11:07:08] doctrine.DEBUG: INSERT INTO compte (numbcompte, solde, partenaire_id) VALUES (?, ?, ?) {"1":389841,"2":0,"3":19} []
[2019-08-05 11:07:08] doctrine.DEBUG: INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"1":"kya","2":["ROLE_ADMIN"],"3":"$argon2i$v=19$m=1024,t=2,p [...]","4":7747544,"5":"diop","6":"kya","7":"km","8":748500222,"9":"actif","10":"kd@gmail.com","11":null,"12":null,"13":19} []
[2019-08-05 11:07:08] doctrine.DEBUG: "ROLLBACK" [] []
[2019-08-05 11:07:08] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["kya", "[\"ROLE_ADMIN\"]", "$argon2i$v=19$m=1024,t=2,p=2$MVh0L3pGY2RjUGpKRy5pbg$BgvrrBagvUaiw0OH9p+flMMxuGO0o7bAFJesDHkfGK0", 7747544, "diop", "kya", "km", 748500222, "actif", "kd@gmail.com", null, null, 19]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677'" at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 55 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"kya\", \"[\\\"ROLE_ADMIN\\\"]\", \"$argon2i$v=19$m=1024,t=2,p=2$MVh0L3pGY2RjUGpKRy5pbg$BgvrrBagvUaiw0OH9p+flMMxuGO0o7bAFJesDHkfGK0\", 7747544, \"diop\", \"kya\", \"km\", 748500222, \"actif\", \"kd@gmail.com\", null, null, 19]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:55, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} []
[2019-08-05 11:07:46] request.INFO: Matched route "userataire_index". {"route":"userataire_index","route_parameters":{"_route":"userataire_index","_controller":"App\\Controller\\PrestataireController::ajout"},"request_uri":"http://localhost/api/ajout","method":"POST"} []
[2019-08-05 11:07:46] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 11:07:46] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:07:46] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:07:46] security.INFO: Basic authentication Authorization header found for user. {"username":"zeynab"} []
[2019-08-05 11:07:46] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["zeynab"] []
[2019-08-05 11:07:46] doctrine.DEBUG: "START TRANSACTION" [] []
[2019-08-05 11:07:46] doctrine.DEBUG: INSERT INTO prestataire (rs, nom, adresse, statut, ninea) VALUES (?, ?, ?, ?, ?) {"1":"sa","2":"diop","3":"km","4":"actif","5":"6e54k"} []
[2019-08-05 11:07:46] doctrine.DEBUG: INSERT INTO compte (numbcompte, solde, partenaire_id) VALUES (?, ?, ?) {"1":687451,"2":0,"3":20} []
[2019-08-05 11:07:46] doctrine.DEBUG: INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"1":"kya","2":["ROLE_ADMIN"],"3":"$argon2i$v=19$m=1024,t=2,p [...]","4":7747544,"5":"diop","6":"kya","7":"km","8":748500222,"9":"actif","10":"kd@gmail.com","11":null,"12":null,"13":20} []
[2019-08-05 11:07:46] doctrine.DEBUG: "ROLLBACK" [] []
[2019-08-05 11:07:46] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["kya", "[\"ROLE_ADMIN\"]", "$argon2i$v=19$m=1024,t=2,p=2$VUk5Z2taVnBVOEsuSkR5ZQ$3NeYphUNeFEuk2G6hGnALaVYYttzX0peOCB7VYPy\/gw", 7747544, "diop", "kya", "km", 748500222, "actif", "kd@gmail.com", null, null, 20]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677'" at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 55 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, roles, password, tel, nom, prenom, adresse, cni, statut, email, image_name, updated_at, partenaire_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"kya\", \"[\\\"ROLE_ADMIN\\\"]\", \"$argon2i$v=19$m=1024,t=2,p=2$VUk5Z2taVnBVOEsuSkR5ZQ$3NeYphUNeFEuk2G6hGnALaVYYttzX0peOCB7VYPy\\/gw\", 7747544, \"diop\", \"kya\", \"km\", 748500222, \"actif\", \"kd@gmail.com\", null, null, 20]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:55, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kya' for key 'UNIQ_8D93D649F85E0677' at /home/seynabou/Documents/neldamoney_solo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} []
[2019-08-05 11:08:47] request.INFO: Matched route "user_register". {"route":"user_register","route_parameters":{"_route":"user_register","_controller":"App\\Controller\\UserController::register"},"request_uri":"http://localhost/api/register","method":"POST"} []
[2019-08-05 11:08:47] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 11:08:47] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:08:47] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:08:47] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-05 11:08:47] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-05 11:08:47] security.INFO: Basic authentication failed for user. {"username":"ndioufa","exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"ndioufa\" not found. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:61)"} []
[2019-08-05 11:18:46] request.INFO: Matched route "depot". {"route":"depot","route_parameters":{"_route":"depot","_controller":"App\\Controller\\DepotController::depot"},"request_uri":"http://localhost/api/depot","method":"POST"} []
[2019-08-05 11:18:46] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[2019-08-05 11:18:46] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:18:46] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Guard\\JWTTokenAuthenticator"} []
[2019-08-05 11:18:46] security.INFO: Basic authentication Authorization header found for user. {"username":"ndioufa"} []
[2019-08-05 11:18:46] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4, t0.tel AS tel_5, t0.nom AS nom_6, t0.prenom AS prenom_7, t0.adresse AS adresse_8, t0.cni AS cni_9, t0.statut AS statut_10, t0.email AS email_11, t0.image_name AS image_name_12, t0.updated_at AS updated_at_13, t0.partenaire_id AS partenaire_id_14 FROM user t0 WHERE t0.username = ? LIMIT 1 ["ndioufa"] []
[2019-08-05 11:18:46] security.INFO: Basic authentication failed for user. {"username":"ndioufa","exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"ndioufa\" not found. at /home/seynabou/Documents/neldamoney_solo/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:61)"} []
